### ISSUE TITLE
Trying to create benchmark, and classes aren't getting set

### ISSUE THREAD

**Issue by withinboredom** [BoomTownROI/boomqueries#9]
Here is what I have so far:
https://gist.github.com/withinboredom/9e57be64d13b133fa8f2

The second "resizing" test results in a dom with no boomquery class added.

Getting this:
![screen shot 2015-06-03 at 5 04 15 pm](https://cloud.githubusercontent.com/assets/1883296/7971412/9a7e5b56-0a12-11e5-91d1-5fbbb0dd5a47.png)

should be this:
![screen shot 2015-06-03 at 5 05 03 pm](https://cloud.githubusercontent.com/assets/1883296/7971430/b6f6726e-0a12-11e5-83c4-048faf2dbfff.png)

**Comment by mfunkie** [comment]
Check out this jsbin: http://jsbin.com/namexoqufa/1/edit?html,output

You're setting the width on the container, but the width of `.stuff` isn't going to get wider or less wide because `.body` grows or shrinks.

BoomQueries works based on the size of the element attached.

**Comment by withinboredom** [comment]
What's strange is that it works fine in jsbin either way, but doesn't work fine when on a plain html page... Either way, I was doing it wrong. Thanks for the heads up. I've updated the gist accordingly for some interesting results.
